"""Per-type data capture, recursive on both sides (§2.2).

Python side uses a ``json.JSONEncoder`` subclass whose ``default()`` handles
nested containers automatically.  R side uses a single recursive dispatcher
(``.r2py_serialize_var``) whose adapters return R lists/scalars; a single outer
``jsonlite::toJSON`` is applied at the top level so the resulting JSON shape
matches what the Python encoder produces.

Unknown types go to uncapturable (EffectBundle.uncapturable), never silently
skipped (D2).
"""
from __future__ import annotations

import datetime as _dt
import json as _json
import math as _math
from pathlib import Path
from typing import Any


def _sanitize_non_finite(obj: Any) -> Any:
    """Replace non-finite floats to match R's jsonlite output.

    nan → None  (jsonlite na='null' maps both NA and NaN to null)
    inf → "Inf", -inf → "-Inf"  (jsonlite wraps in strings)
    """
    if isinstance(obj, float):
        if _math.isnan(obj):
            return None
        if _math.isinf(obj):
            return "Inf" if obj > 0 else "-Inf"
        return obj
    if isinstance(obj, dict):
        return {k: _sanitize_non_finite(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize_non_finite(v) for v in obj]
    return obj


# ---------------------------------------------------------------------------
# Module-level _R2PyEncoder — used by callers that need to serialize R-side
# captured data (e.g. loop._write_data_sidecar).  The Python preamble text
# generated by build_py_preamble() defines an *equivalent* class inline so the
# sandbox doesn't need to import this module.  Keep the two in lockstep.
# ---------------------------------------------------------------------------

class _R2PyEncoder(_json.JSONEncoder):
    def default(self, obj: Any) -> Any:
        try:
            import numpy as _np  # type: ignore[import]
            if isinstance(obj, _np.generic):
                return obj.item()
            if isinstance(obj, _np.ndarray):
                return obj.tolist()
        except ImportError:
            pass
        if isinstance(obj, _dt.datetime):
            return obj.strftime("%Y-%m-%dT%H:%M:%S")
        if isinstance(obj, _dt.date):
            return obj.isoformat()
        try:
            import pandas as _pd  # type: ignore[import]
            if isinstance(obj, _pd.Timestamp):
                return None if _pd.isna(obj) else obj.strftime("%Y-%m-%dT%H:%M:%S")
            if isinstance(obj, _pd.DataFrame):
                result: dict = {}
                for _c in obj.columns:
                    _series = obj[_c]
                    if _pd.api.types.is_datetime64_any_dtype(_series):
                        result[_c] = [None if _pd.isna(v) else v.strftime("%Y-%m-%d") for v in _series]
                    else:
                        result[_c] = _series.tolist()
                return result
            if isinstance(obj, _pd.Series):
                if _pd.api.types.is_datetime64_any_dtype(obj):
                    return [None if _pd.isna(v) else v.strftime("%Y-%m-%d") for v in obj]
                return obj.tolist()
            if isinstance(obj, _pd.Categorical):
                return list(obj)
        except ImportError:
            pass
        if isinstance(obj, (set, frozenset)):
            return list(obj)
        return super().default(obj)


# ---------------------------------------------------------------------------
# R adapter registry — recursive (serializers return R objects, not JSON)
# ---------------------------------------------------------------------------

# Each entry: (R predicate expression, R serializer expression).  Both use
# ``{var}`` as the placeholder for the current value.  The serializer must
# return an R object (list / atomic vector / scalar) — NOT a JSON string —
# so the outer ``jsonlite::toJSON`` at the top of the epilogue can produce a
# single coherent JSON document.  Container serializers should call
# ``.r2py_serialize_var()`` recursively on their elements.
_R_ADAPTERS: list[tuple[str, str]] = []


def register_r_adapter(type_pred: str, serializer: str) -> None:
    """Register an R-side adapter.  See module docstring for the contract."""
    _R_ADAPTERS.append((type_pred, serializer))


# Built-in R adapters — ordered most-specific first.
# Date / POSIXct → ISO strings (mirrors Python's .isoformat()).
register_r_adapter(
    "inherits({var}, 'Date')",
    "format({var}, '%Y-%m-%d')",
)
register_r_adapter(
    "inherits({var}, 'POSIXct') || inherits({var}, 'POSIXlt')",
    "format({var}, '%Y-%m-%dT%H:%M:%S')",
)
# Factor → character vector (mirrors pandas.Categorical → list(obj)).
register_r_adapter(
    "is.factor({var})",
    "as.character({var})",
)
# data.frame → dict of column-name → recursed column.
register_r_adapter(
    "is.data.frame({var})",
    "lapply({var}, .r2py_serialize_var)",
)
# htmltools / shiny tags → rendered HTML string.
register_r_adapter(
    "inherits({var}, 'htmltools_tag') || inherits({var}, 'shiny.tag')",
    "as.character(htmltools::renderTags({var})$html)",
)
# lm / glm → structured summary, each component recursed.
register_r_adapter(
    "inherits({var}, 'lm') || inherits({var}, 'glm')",
    (
        "list("
        "coefficients = .r2py_serialize_var(as.list(coef({var})))"
        ", residuals = .r2py_serialize_var(as.list(residuals({var})))"
        ", fitted = .r2py_serialize_var(as.list(fitted({var})))"
        ")"
    ),
)
# S4 objects → dict of slot-name → recursed slot.
register_r_adapter(
    "isS4({var})",
    (
        "{ .r2py_slots <- slotNames({var}); "
        ".r2py_res <- lapply(.r2py_slots, function(.s) .r2py_serialize_var(slot({var}, .s))); "
        "names(.r2py_res) <- .r2py_slots; "
        ".r2py_res }"
    ),
)
# Generic list (including named lists) → recurse into elements.
register_r_adapter(
    "is.list({var})",
    "lapply({var}, .r2py_serialize_var)",
)
# vctrs_vctr (haven_labelled, etc.) → strip class so jsonlite doesn't recurse.
register_r_adapter(
    "inherits({var}, 'vctrs_vctr')",
    "unclass({var})",
)
# Plain atomic vectors / scalars → return as-is; jsonlite encodes them at the top.
register_r_adapter(
    "is.atomic({var}) || is.numeric({var}) || is.character({var}) || is.logical({var})",
    "{var}",
)


# ---------------------------------------------------------------------------
# Preamble / epilogue generators
# ---------------------------------------------------------------------------

R_PREAMBLE = """\
library(jsonlite)
.r2py_uncapturable <- character(0)
"""


def build_r_serializer_fn() -> str:
    """Return R code defining ``.r2py_serialize_var(.r2py_obj)``.

    The function dispatches on the registered adapters in registration order.
    Each adapter's serializer returns an R object (list / vector / scalar).
    Functions and environments return ``NULL`` (uncapturable).  Anything that
    raises or has no matching adapter returns the string ``'__uncapturable__'``
    so the caller can route it to the uncapturable list.

    Note: ``'__uncapturable__'`` is a sentinel string returned from this
    function, NOT a JSON value — callers must check for it before serializing.
    """
    dispatch_lines: list[str] = []
    for i, (pred_tmpl, ser_tmpl) in enumerate(_R_ADAPTERS):
        pred = pred_tmpl.replace("{var}", ".r2py_obj")
        ser = ser_tmpl.replace("{var}", ".r2py_obj")
        keyword = "if" if i == 0 else "} else if"
        dispatch_lines.append(f"    {keyword} ({pred}) {{")
        dispatch_lines.append(f"      tryCatch({ser}, error = function(e) '__uncapturable__')")
    if dispatch_lines:
        dispatch_lines.append("    } else {")
        dispatch_lines.append("      '__uncapturable__'")
        dispatch_lines.append("    }")
    else:
        dispatch_lines.append("    '__uncapturable__'")
    body = "\n".join(dispatch_lines)
    return (
        ".r2py_serialize_var <- function(.r2py_obj) {\n"
        "  if (is.null(.r2py_obj)) return(NULL)\n"
        "  if (is.environment(.r2py_obj)) return(NULL)\n"
        "  if (is.function(.r2py_obj)) {\n"
        "    .r2py_cls <- class(.r2py_obj)\n"
        "    if (identical(.r2py_cls, 'function')) return(NULL)\n"
        "    .r2py_fmls <- tryCatch(names(formals(.r2py_obj)), error = function(e) character(0))\n"
        "    .r2py_attrs <- list()\n"
        "    for (.r2py_an in c('name', 'dispatch_args')) {\n"
        "      .r2py_av <- tryCatch(attr(.r2py_obj, .r2py_an), error = function(e) NULL)\n"
        "      if (!is.null(.r2py_av)) .r2py_attrs[[.r2py_an]] <- .r2py_av\n"
        "    }\n"
        "    return(list(\n"
        "      `__r2py_callable_meta__` = TRUE,\n"
        "      class = as.list(.r2py_cls),\n"
        "      formals = as.list(.r2py_fmls),\n"
        "      attributes = .r2py_attrs\n"
        "    ))\n"
        "  }\n"
        "  tryCatch({\n"
        f"{body}\n"
        "  }, error = function(e) '__uncapturable__')\n"
        "}\n"
    )


def build_r_epilogue() -> str:
    """Build the R data capture epilogue from the current ``_R_ADAPTERS``.

    Walks ``.GlobalEnv``, recursively serializes each variable via
    ``.r2py_serialize_var``, assembles them into a single R named list, then
    emits one coherent JSON document via ``jsonlite::toJSON``.  Uncapturable
    variables are recorded separately.
    """
    return (
        build_r_serializer_fn()
        + "# r2py data capture: serialize all globals to _r2py_state.json\n"
        ".r2py_state <- list()\n"
        ".r2py_vars <- ls(envir = .GlobalEnv)\n"
        ".r2py_vars <- .r2py_vars[!startsWith(.r2py_vars, '.r2py_')]\n"
        "for (.r2py_v in .r2py_vars) {\n"
        "  .r2py_obj <- get(.r2py_v, envir = .GlobalEnv)\n"
        "  .r2py_serialized <- .r2py_serialize_var(.r2py_obj)\n"
        "  if (is.null(.r2py_serialized) || identical(.r2py_serialized, '__uncapturable__')) {\n"
        "    .r2py_uncapturable <- c(.r2py_uncapturable, .r2py_v)\n"
        "  } else {\n"
        "    .r2py_state[[.r2py_v]] <- .r2py_serialized\n"
        "  }\n"
        "}\n"
        "writeLines(jsonlite::toJSON(.r2py_state, auto_unbox=TRUE, na='null', force=TRUE), '_r2py_state.json')\n"
        "writeLines(jsonlite::toJSON(.r2py_uncapturable), '_r2py_uncapturable.json')\n"
    )


# ---------------------------------------------------------------------------
# Python preamble — installs _R2PyEncoder + _r2py_try_serialize helper
# ---------------------------------------------------------------------------

PY_EPILOGUE_TEMPLATE = """\
import json as _r2py_json

_r2py_state = {}
_r2py_uncapturable = []

for _r2py_k, _r2py_v in list(globals().items()):
    if _r2py_k.startswith('_r2py_') or _r2py_k.startswith('__'):
        continue
    if callable(_r2py_v) and not isinstance(_r2py_v, type):
        _r2py_vtype = type(_r2py_v)
        _r2py_tname = _r2py_vtype.__name__
        if _r2py_tname in ('function', 'builtin_function_or_method', 'method',
                            'method-wrapper', 'method_descriptor'):
            continue
        import inspect as _r2py_inspect
        try:
            _r2py_sig = _r2py_inspect.signature(_r2py_v)
            _r2py_fmls = list(_r2py_sig.parameters.keys())
        except (ValueError, TypeError):
            _r2py_fmls = []
        if set(_r2py_fmls) <= {'args', 'kwargs', 'self', 'cls'}:
            for _r2py_wattr in dir(_r2py_v):
                if _r2py_wattr.startswith('__') and _r2py_wattr != '__wrapped__':
                    continue
                _r2py_inner = getattr(_r2py_v, _r2py_wattr, None)
                if _r2py_inner is None or not callable(_r2py_inner) or type(_r2py_inner).__name__ != 'function':
                    continue
                try:
                    _r2py_inner_fmls = list(_r2py_inspect.signature(_r2py_inner).parameters.keys())
                    if not set(_r2py_inner_fmls) <= {'args', 'kwargs', 'self', 'cls'}:
                        _r2py_fmls = _r2py_inner_fmls
                        break
                except (ValueError, TypeError):
                    pass
        _r2py_meta = {
            '__r2py_callable_meta__': True,
            'class': [_r2py_vtype.__name__],
            'formals': _r2py_fmls,
            'attributes': {},
        }
        for _r2py_an in ('name', 'dispatch_args'):
            _r2py_av = getattr(_r2py_v, _r2py_an, None)
            if _r2py_av is not None:
                _r2py_meta['attributes'][_r2py_an] = _r2py_av
        _r2py_state[_r2py_k] = _r2py_meta
        continue
    _r2py_serialized, _r2py_ok = _r2py_try_serialize(_r2py_k, _r2py_v)
    if not _r2py_ok:
        _r2py_uncapturable.append(_r2py_k)
        continue
    if isinstance(_r2py_serialized, dict) and '__r2py_callable_meta__' in _r2py_serialized:
        _r2py_serialized = {k: v for k, v in _r2py_serialized.items() if k != '__r2py_callable_meta__'}
    _r2py_state[_r2py_k] = _r2py_serialized

with open('_r2py_state.json', 'w', encoding='utf-8') as _f:
    _r2py_json.dump(_r2py_state, _f)
with open('_r2py_uncapturable.json', 'w', encoding='utf-8') as _f:
    _r2py_json.dump(_r2py_uncapturable, _f)
"""


def build_py_preamble() -> str:
    """Build the Python preamble that installs the encoder + helper.

    The encoder's ``default()`` does an ``isinstance`` cascade and is invoked
    recursively by ``json.dumps`` for every non-native element encountered in
    the object graph — including elements inside lists / dicts returned from
    ``default()`` itself.  This is the structural fix for the v0.1
    JSON-opacity trap (nested ``datetime.date`` inside a DataFrame column,
    nested ``np.generic`` inside a Series, etc.).

    Adding a new supported type = one ``isinstance`` branch in ``default()``.
    """
    return """\
import json as _r2py_json
import datetime as _r2py_dt
import math as _r2py_math


def _r2py_sanitize(obj):
    if isinstance(obj, float):
        if _r2py_math.isnan(obj):
            return None
        if _r2py_math.isinf(obj):
            return "Inf" if obj > 0 else "-Inf"
        return obj
    if isinstance(obj, dict):
        return {k: _r2py_sanitize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_r2py_sanitize(v) for v in obj]
    return obj


class _R2PyEncoder(_r2py_json.JSONEncoder):
    def default(self, obj):
        # numpy scalars and arrays
        try:
            import numpy as _np
            if isinstance(obj, _np.generic):
                return obj.item()
            if isinstance(obj, _np.ndarray):
                return obj.tolist()
        except ImportError:
            pass
        # datetime — datetime before date (datetime is a subclass of date)
        if isinstance(obj, _r2py_dt.datetime):
            return obj.strftime('%Y-%m-%dT%H:%M:%S')
        if isinstance(obj, _r2py_dt.date):
            return obj.isoformat()
        # pandas
        try:
            import pandas as _pd
            if isinstance(obj, _pd.Timestamp):
                return None if _pd.isna(obj) else obj.strftime('%Y-%m-%dT%H:%M:%S')
            if isinstance(obj, _pd.DataFrame):
                result = {}
                for _c in obj.columns:
                    _series = obj[_c]
                    if _pd.api.types.is_datetime64_any_dtype(_series):
                        result[_c] = [None if _pd.isna(v) else v.strftime('%Y-%m-%d') for v in _series]
                    else:
                        result[_c] = _series.tolist()
                return result
            if isinstance(obj, _pd.Series):
                if _pd.api.types.is_datetime64_any_dtype(obj):
                    return [None if _pd.isna(v) else v.strftime('%Y-%m-%d') for v in obj]
                return obj.tolist()
            if isinstance(obj, _pd.Categorical):
                return list(obj)
        except ImportError:
            pass
        # sets — useful for env captures
        if isinstance(obj, (set, frozenset)):
            return list(obj)
        return super().default(obj)


def _r2py_try_serialize(name, obj):
    \"\"\"Round-trip ``obj`` through ``_R2PyEncoder``, sanitizing non-finite floats.

    Returns ``(json_safe_value, True)`` on success — the value is pure Python
    (dict/list/str/number/bool/None) and can be re-serialized without a custom
    encoder.  Returns ``(None, False)`` for anything the encoder cannot handle.
    \"\"\"
    try:
        raw = _r2py_json.dumps(obj, cls=_R2PyEncoder, allow_nan=True)
        return _r2py_sanitize(_r2py_json.loads(raw, parse_constant=lambda c: {
            'NaN': None, 'Infinity': 'Inf', '-Infinity': '-Inf',
        }.get(c))), True
    except (TypeError, ValueError):
        return None, False
"""


# ---------------------------------------------------------------------------
# Collect
# ---------------------------------------------------------------------------

def collect(workdir: Path) -> dict:
    """Read _r2py_state.json and _r2py_uncapturable.json → EffectBundle fields.

    Backward-compatible: handles both the new R format (single coherent JSON
    document with structured values) and the legacy format (per-variable JSON
    strings that need a second ``json.loads`` pass).
    """
    import json

    data: dict = {}
    uncapturable: list[str] = []

    state_file = workdir / "_r2py_state.json"
    if state_file.exists():
        try:
            raw = json.loads(state_file.read_text(encoding="utf-8"))
            for k, v in raw.items():
                # Legacy R epilogue stored values as JSON-encoded strings; the
                # new epilogue stores them as structured values.  Try decode
                # for the legacy case only — fall through for already-decoded.
                if isinstance(v, str):
                    try:
                        decoded = json.loads(v)
                    except (json.JSONDecodeError, ValueError):
                        decoded = v
                    data[k] = decoded
                else:
                    data[k] = v
        except Exception:
            pass

    unc_file = workdir / "_r2py_uncapturable.json"
    if unc_file.exists():
        try:
            uncapturable = json.loads(unc_file.read_text(encoding="utf-8"))
        except Exception:
            pass

    return {"data": data, "uncapturable": uncapturable}


# ---------------------------------------------------------------------------
# Sidecar payload helper (used by loop.py and stage4/verifier.py)
# ---------------------------------------------------------------------------

def serialize_bundle_data(data: dict, *, indent: int | None = None) -> str:
    """Serialize an EffectBundle.data dict to JSON via ``_R2PyEncoder``.

    Single source of truth for the data-loading shim's payload format — used
    both by ``loop._write_data_sidecar`` (on-disk artifact for manual debugging)
    and ``stage4.verifier._build_sidecar_payload`` (in-sandbox copy for
    equivalence testing).  Keeping these two paths in lockstep ensures a new
    type added to ``_R2PyEncoder`` is automatically supported by both.
    """
    encoded = _json.loads(_json.dumps(data or {}, cls=_R2PyEncoder, allow_nan=True))
    return _json.dumps(_sanitize_non_finite(encoded), indent=indent)
